/**
  ******************************************************************************
  * Author  VMA Application Team (mv737)
  * Version V1.0.7
  * Date    4-April-2016
  * Brief   Node-locked license for osx_motion_fx module
  ******************************************************************************
  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ******************************************************************************
  */


#ifndef _OSX_MOTION_FX_LICENSE_
#define _OSX_MOTION_FX_LICENSE_
uint32_t osx_mfx_license[3][4] =
{
    { 0xEF6B9017, 0x53AF95E8, 0xF2DEB2BF, 0x09D77DF1 },
	{ 0x387C94D8, 0xB44A72E9, 0xD85F2D6F, 0x19967F07 },
	{ 0x93985012, 0x4AD0AA2A, 0x6F4A473E, 0xEB77F6F7 } 
}; 
#endif /* _OSX_MOTION_FX_LICENSE_ */
